<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Hostel;
use AppBundle\Entity\ServiceClassification;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * RoomServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
