controllers:
  type: rest
  resource: "@AppBundle/RestApi/"

hostels:
  type: rest
  resource: AppBundle\RestApi\HostelController

rooms:
  type: rest
  resource: AppBundle\RestApi\RoomController
  parent: hostels

fos_comment_api:
  type: rest
  resource: "@FOSCommentBundle/Resources/config/routing.yml"
  prefix: /api
  defaults: { _format: html }